# Site settings
title: oskari heinonen
email: osheinonen@gmail.com
description: Hello! My name is Oskari. I'm a Front End Developer / Designer

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://osheinonen.github.io/' # the base hostname & protocol for your site

exclude: [
  .git,
  .gitignore
  .DS_Store,
  node_modules,
  package.json,
  Gruntfile.js,
  README.md,
  Gemfile,
  Gemfile.lock,
  LICENSE,
  _sass
]

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: "_posts"
        type: "posts"
      values:
        reading_time: true
        show_tags: true
        show_categories: true
